### ISSUE TITLE
How to work with this

### ISSUE THREAD

**Issue by KRav007** [jcoreio/redux-form-normalize-on-blur#1]
I inserted this:   normalizeOnBlur={value => value && value.trim()}

to my field and I get "value.trim is not a function....."

Cause the comp. didn't knew the value

I would like to use a function for validation like this:

normalizeOnBlur={normalizeOnBlurBirthdayTT}

**Comment by jedwards1211** [comment]
Sorry for the delay, GitHub for some reason didn't make me a watcher by default.
What version of `redux-form` are you using, and what `component` are you using on your `NormalizeOnBlurField`?

**Comment by jedwards1211** [comment]
I'm going to close this due to inactivity.  If you have any more questions feel free to continue commenting in this thread.
