### ISSUE TITLE
Immutable version not working as expected.

### ISSUE THREAD

**Issue by fobus42** [jcoreio/redux-form-normalize-on-blur#4]

**Comment by jedwards1211** [comment]
Did you get any particular error message? I was just on vacation but I'll look into this in the next few days.

**Comment by jedwards1211** [comment]
@fobus42 there are tests for the immutable version.  What problem are you having?

**Comment by fobus42** [comment]
I'm really sorry, I didn't know that this thread is live. I have fixed my problem and created this topic mistakenly.

**Comment by jedwards1211** [comment]
No worries, glad you got it working :)
